import * as THREE from 'three';
import './style.css';
import {art} from './art.js';
import {createCorridor} from './corridor.js';
const $=s=>document.querySelector(s),overlay=$('#overlay'),room=$('#room'),canvas=$('#world');
const state={mode:'corridor',evidence:new Set(),contradiction:false,ended:false};
const evidence={file:{title:'01 / Материалы дела',body:'В 22:15 в архиве участка найден мёртвым журналист Антон Ветров. Он готовил публикацию о подмене улик. Причина смерти — удар тяжёлым предметом. Пропал диктофон. Последним посетителем был капитан Сергей Орлов.'},log:{title:'02 / Журнал пропусков',body:'Электронный пропуск С. Орлова использован у архивного входа в 21:58 и на выходе в 22:11. Его утверждение, что он покинул участок в 21:30, противоречит журналу.'},record:{title:'03 / Восстановленная запись',body:'Эксперт восстановил аудио с телефона Ветрова. 22:06: «Сергей, я передал копии редактору. Твои угрозы ничего не изменят». Затем слышен удар. Запись, пропуск и показания связывают Орлова с убийством.'}};
let audio;
function sound(){if(audio)return;try{audio=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=58;g.gain.value=.018;o.connect(g).connect(audio.destination);o.start();}catch{}}
function release(){if(document.pointerLockElement)document.exitPointerLock();keys.clear();}
function panel(html){release();overlay.innerHTML=`<section class="panel"><button class="close" aria-label="Закрыть">×</button>${html}</section>`;$('.close').onclick=close;}
function close(){overlay.innerHTML='';}
function toast(text){const d=document.createElement('div');d.className='toast';d.textContent=text;document.body.append(d);setTimeout(()=>d.remove(),3500);}
function collect(id){const fresh=!state.evidence.has(id);state.evidence.add(id);$('#count').textContent=`${state.evidence.size}/3`;panel(`<div class="eyebrow">АРХИВ УЧАСТКА · ДЕЛО № 041</div><h2>${evidence[id].title}</h2><p class="lead">${evidence[id].body}</p><div class="rule"></div><div class="badge">ДОБАВЛЕНО В МАТЕРИАЛЫ ДЕЛА</div>`);if(fresh)toast('Новая улика добавлена в дело');}
function journal(){panel(`<div class="eyebrow">РАССЛЕДОВАНИЕ / ${state.evidence.size} ИЗ 3 УЛИК</div><h2>Смерть в архиве</h2><p>Проверьте документы в кабинете следователя, затем сопоставьте их с показаниями Орлова.</p>${Object.entries(evidence).map(([id,e])=>`<div class="evidence"><strong>${state.evidence.has(id)?e.title:'Неизученный материал'}</strong><p>${state.evidence.has(id)?e.body:'Продолжите расследование, чтобы открыть эту улику.'}</p></div>`).join('')}`);}
$('#journal').onclick=journal;
function dialog(reply='Орлов сидит неподвижно. «Я уже всё рассказал. Ветров был жив, когда я уходил».'){panel(`<div class="eyebrow">ДОПРОС / КАПИТАН СЕРГЕЙ ОРЛОВ</div><h2>«Мне нечего скрывать»</h2><p class="lead">${reply}</p><div class="rule"></div><button class="choice" data-q="alibi">Где вы были в момент убийства?</button><button class="choice" data-q="motive">Что связывало вас с Ветровым?</button>${state.evidence.has('log')?'<button class="choice" data-q="proof">Предъявить журнал: ваш пропуск использован в 22:11.</button>':''}${state.evidence.has('record')?'<button class="choice" data-q="audio">Предъявить восстановленную запись.</button>':''}<button class="choice" data-q="verdict">Завершить расследование →</button>`);document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{const q=b.dataset.q;if(q==='alibi')dialog('«Я ушёл в 21:30. После этого поехал домой. Никого в архиве не видел».');if(q==='motive')dialog('«Он собирался опубликовать грязную статью обо мне. Но за статьи не убивают».');if(q==='proof'){state.contradiction=true;dialog('Орлов отводит взгляд. «Хорошо. Я вернулся. Хотел поговорить. Но запись с камеры исчезла — вы ничего не докажете». Теперь стоит запросить экспертизу через телефон в кабинете следователя.');}if(q==='audio')dialog('«Он грозился разрушить мою жизнь…» Орлов замолкает. Его версия больше не совпадает с доказательствами.');if(q==='verdict')verdict();});}
function verdict(){panel(`<div class="eyebrow">РЕШЕНИЕ СЛЕДОВАТЕЛЯ</div><h2>Кто ответит за убийство?</h2><p>Обвинение требует доказательств. Ваше решение завершит дело.</p><button class="choice" id="accuse">Обвинить Сергея Орлова</button><button class="choice" id="free">Освободить Орлова — доказательств недостаточно</button><button class="choice" id="continue">Продолжить расследование</button>`);$('#continue').onclick=()=>dialog();$('#accuse').onclick=()=>ending(state.evidence.size===3&&state.contradiction?'solved':'weak');$('#free').onclick=()=>ending('free');}
function ending(result){state.ended=true;const endings={solved:['Дело раскрыто','Запись, журнал пропусков и противоречивые показания подтверждают обвинение. Орлов задержан. Материалы Ветрова переданы редакции.'],weak:['Обвинение рассыпалось','Подозрение оказалось верным, но доказательства не были собраны и сопоставлены. Суд отклонил обвинение. Орлов вышел на свободу.'],free:['Дело осталось открытым','Орлов покинул участок. Наутро архивные материалы исчезли. Теперь установить правду будет гораздо труднее.']};panel(`<div class="eyebrow">НОЧНАЯ СМЕНА / ИТОГ ДЕЛА</div><h2>${endings[result][0]}</h2><p class="lead">${endings[result][1]}</p><div class="badge">СОБРАНО УЛИК: ${state.evidence.size}/3</div><button class="primary" id="restart">НАЧАТЬ ЗАНОВО</button>`);$('#restart').onclick=()=>{state.evidence.clear();state.contradiction=false;state.ended=false;$('#count').textContent='0/3';exitRoom();close();intro();};}
function enter(type){release();state.mode=type;room.hidden=false;$('#crosshair').hidden=true;$('#hint').textContent='';$('#location').textContent=type==='office'?'УЧАСТОК № 7 · КАБИНЕТ СЛЕДОВАТЕЛЯ':'УЧАСТОК № 7 · КОМНАТА ДОПРОСА';$('#controls').textContent='МЫШЬ — осмотр и взаимодействие / ESC — пауза';room.innerHTML=`<div class="scene">${art(type)}</div><div class="room-caption">${type==='office'?'01 / МАТЕРИАЛЫ РАССЛЕДОВАНИЯ':'02 / ПОКАЗАНИЯ'}<h2>${type==='office'?'Кабинет следователя':'Комната допроса'}</h2></div><button class="back">← В КОРИДОР</button>`;$('.back').onclick=exitRoom;const spots=type==='office'?[['Папка дела',34,70,15,14,()=>collect('file')],['Доска улик',68,18,25,34,()=>collect('log')],['Телефон · экспертиза',66,72,10,11,()=>{if(state.contradiction)collect('record');else panel('<div class="eyebrow">ЭКСПЕРТНЫЙ ОТДЕЛ</div><h2>Нужна зацепка</h2><p>Сначала изучите журнал пропусков и предъявите его подозреваемому. Его ответ поможет определить, что искать экспертам.</p>');}]]:[['Допросить Орлова',47,26,18,38,()=>dialog()],['Протокол допроса',34,70,15,13,()=>dialog()],['Материалы дела',69,68,8,14,journal]];for(const [label,x,y,w,h,fn]of spots){const b=document.createElement('button');b.className='hotspot';b.setAttribute('aria-label',label);b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;b.innerHTML=`<span>${label}</span>`;b.onclick=fn;room.append(b);}}
function exitRoom(){state.mode='corridor';room.hidden=true;$('#crosshair').hidden=false;$('#location').textContent='УЧАСТОК № 7 · 2 ЭТАЖ';$('#controls').textContent='W A S D — движение / МЫШЬ — обзор / ЛКМ — открыть дверь';}
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;const scene=new THREE.Scene();scene.background=new THREE.Color('#101b22');scene.fog=new THREE.Fog('#101b22',8,25);const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,40);camera.position.set(0,1.65,5);camera.rotation.order='YXZ';const {doors,updateStreet}=createCorridor(scene,renderer);
const ray=new THREE.Raycaster(),keys=new Set();let target=null,busy=false,yaw=0,pitch=0;
document.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(overlay.innerHTML)close();else pause();}if(!overlay.innerHTML)keys.add(e.code);});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',release);
document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state.mode==='corridor'&&!overlay.innerHTML){yaw-=e.movementX*.002;pitch=Math.max(-1.2,Math.min(1.2,pitch-e.movementY*.002));camera.rotation.set(pitch,yaw,0);}});
canvas.addEventListener('click',async()=>{if(state.mode!=='corridor'||overlay.innerHTML||busy)return;sound();if(target){if(target.userData.type==='locked'){toast('Архив опечатан. Начните с кабинета следователя.');return;}busy=true;release();const selected=target;const hinge=selected.userData.hinge;const start=hinge.rotation.y;let t=0;const animate=()=>{t+=.07;hinge.rotation.y=start-Math.min(t,1)*1.15;if(t<1)requestAnimationFrame(animate);else{enter(selected.userData.type);hinge.rotation.y=start;busy=false;}};animate();}else{try{await canvas.requestPointerLock();}catch{toast('Нажмите на коридор для управления мышью');}}});
function pause(){panel('<div class="eyebrow">НОЧНАЯ СМЕНА</div><h2>Пауза</h2><p>В коридоре: WASD и мышь. Посмотрите на дверь с расстояния до 2,6 м и нажмите ЛКМ. В кабинете: наведите курсор на предметы.</p><button class="primary" id="resume">ПРОДОЛЖИТЬ</button>');$('#resume').onclick=close;}
function intro(){panel('<div class="eyebrow">ИНТЕРАКТИВНЫЙ ДЕТЕКТИВ / ПРОТОТИП</div><h1>Ночная<br>смена</h1><p class="lead">В участке убит журналист.<br>Подозреваемый — один из ваших коллег.</p><div class="rule"></div><div class="intro-meta"><span>ДЕЛО № 041</span><span>ОДНА НОЧЬ</span><span>ТРИ УЛИКИ</span></div><p>Изучите документы в кабинете следователя, найдите противоречия на допросе и решите, кому предъявить обвинение.</p><button class="primary" id="begin">ПРИСТУПИТЬ К РАССЛЕДОВАНИЮ →</button>');$('.close').hidden=true;$('#begin').onclick=()=>{close();sound();toast('Нажмите на коридор, чтобы управлять взглядом');};}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(state.mode==='corridor'&&!overlay.innerHTML&&!busy){let x=0,z=0;if(keys.has('KeyW'))z-=1;if(keys.has('KeyS'))z+=1;if(keys.has('KeyA'))x-=1;if(keys.has('KeyD'))x+=1;const len=Math.hypot(x,z)||1;const dx=(x*Math.cos(yaw)+z*Math.sin(yaw))/len*dt*2.6,dz=(-x*Math.sin(yaw)+z*Math.cos(yaw))/len*dt*2.6;camera.position.x=THREE.MathUtils.clamp(camera.position.x+dx,-2.35,2.35);camera.position.z=THREE.MathUtils.clamp(camera.position.z+dz,-16.5,6.5);ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(doors)[0];target=hit&&hit.distance<2.6?hit.object:null;$('#hint').textContent=target?(target.userData.type==='locked'?'АРХИВ ОПЕЧАТАН':'ЛКМ — '+(target.userData.type==='office'?'КАБИНЕТ СЛЕДОВАТЕЛЯ':'КОМНАТА ДОПРОСА')):(document.pointerLockElement?'':'ЛКМ — управление взглядом');}if(state.mode==='corridor'){updateStreet(now/1000);renderer.render(scene,camera);}}requestAnimationFrame(frame);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});intro();
if (import.meta.env.DEV) window.__nightShift = { state, camera };
