import * as THREE from 'three';
import './style.css';
import {art} from './art.js';
import {createCorridor} from './corridor.js';
import {createMenus} from './menu.js';
import {createTutorial} from './tutorial.js';
const tutorial=createTutorial();
const $=s=>document.querySelector(s),overlay=$('#overlay'),room=$('#room'),canvas=$('#world');
const state={mode:'corridor',evidence:new Set(),contradiction:false,ended:false};
const evidence={
  file:{title:'01 / Дело «Последний раунд»',body:'В 22:15 после благотворительного турнира в раздевалке клуба «Ринг» найден убитым спортивный журналист Илья Громов. Рядом лежал металлический кубок со следами крови. Громов расследовал договорные бои. Боксёрша Марина Соколова, известная как «Сирень», публично поссорилась с ним перед финалом. В 23:20 её доставили в участок прямо с тренировки.'},
  log:{title:'02 / Журнал доступа в клуб',body:'Личный пропуск Марины Соколовой зарегистрирован у служебного входа в 21:58 и на выходе в 22:11. Время смерти Громова — между 22:00 и 22:10. Соколова утверждает, что ушла в 21:30. Её версия не совпадает с журналом.'},
  record:{title:'03 / Запись и заключение эксперта',body:'Эксперт восстановил запись на телефоне Громова. В 22:06 он говорит: «Марина, поставь кубок. Редакция уже получила доказательства договорного боя». Слышен её ответ: «Ты обещал не трогать мою сестру!», затем удар. Эксперт подтвердил голос Соколовой и обнаружил её отпечатки на кубке с кровью Громова. Запись и экспертиза подтверждают журнал доступа.'}
};
let audio,audioGain;
function sound(){if(audio){audio.resume().catch(()=>{});return;}try{audio=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=58;audioGain=g;g.gain.value=.028*menus.preferences.volume/100;o.connect(g).connect(audio.destination);o.start();}catch{}}
function release(){if(document.pointerLockElement)document.exitPointerLock();keys.clear();}
function panel(html){release();overlay.innerHTML=`<section class="panel"><button class="close" aria-label="Закрыть">×</button>${html}</section>`;$('.close').onclick=close;}
function close(){overlay.innerHTML='';captureMouse();}
let mouseCapturePending=false;
async function captureMouse(){
  if(!menus.playing||state.mode!=='corridor'||overlay.innerHTML||state.ended||document.pointerLockElement===canvas||mouseCapturePending)return;
  mouseCapturePending=true;
  try{await canvas.requestPointerLock();}
  catch{if(menus.playing&&state.mode==='corridor'&&!overlay.innerHTML)toast('Нажмите на сцену, чтобы вернуть управление мышью.');}
  finally{mouseCapturePending=false;}
}
// If a menu opens while a browser request is pending, do not lock its cursor.
document.addEventListener('pointerlockchange',()=>{
  if(document.pointerLockElement===canvas&&(!menus.playing||state.mode!=='corridor'||overlay.innerHTML))document.exitPointerLock();
});
function toast(text){const d=document.createElement('div');d.className='toast';d.textContent=text;document.body.append(d);setTimeout(()=>d.remove(),3500);}
function collect(id){const fresh=!state.evidence.has(id);state.evidence.add(id);$('#count').textContent=`${state.evidence.size}/3`;panel(`<div class="eyebrow">АРХИВ УЧАСТКА · ДЕЛО № 041</div><h2>${evidence[id].title}</h2><p class="lead">${evidence[id].body}</p><div class="rule"></div><div class="badge">ДОБАВЛЕНО В МАТЕРИАЛЫ ДЕЛА</div>`);if(fresh)toast('Новая улика добавлена в дело');}
function journal(){panel(`<div class="eyebrow">РАССЛЕДОВАНИЕ / ${state.evidence.size} ИЗ 3 УЛИК</div><h2>Последний раунд</h2><p>Проверьте документы в кабинете следователя, затем сопоставьте их с показаниями Соколовой.</p>${Object.entries(evidence).map(([id,e])=>`<div class="evidence"><strong>${state.evidence.has(id)?e.title:'Неизученный материал'}</strong><p>${state.evidence.has(id)?e.body:'Продолжите расследование, чтобы открыть эту улику.'}</p></div>`).join('')}`);}
$('#journal').onclick=journal;
function dialog(reply='Соколова сжимает красные перчатки. «Я приехала с тренировки. Илья был жив, когда я ушла. Вы задержали не того человека».'){
  panel(`<div class="eyebrow">ДОПРОС / МАРИНА «СИРЕНЬ» СОКОЛОВА</div><h2>«Я не убийца»</h2><p class="lead">${reply}</p><div class="rule"></div><button class="choice" data-q="alibi">Когда вы покинули клуб?</button><button class="choice" data-q="motive">Почему вы поссорились с Громовым?</button>${state.evidence.has('log')?'<button class="choice" data-q="proof">Предъявить журнал: ваш пропуск использован в 22:11.</button>':''}${state.evidence.has('record')?'<button class="choice" data-q="audio">Предъявить запись и заключение эксперта.</button>':''}<button class="choice" data-q="verdict">Завершить расследование →</button>`);
  document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{
    const q=b.dataset.q;tutorial.finish();
    if(q==='alibi')dialog('«В 21:30. После боя я уехала тренироваться в другой зал. В раздевалку больше не заходила».');
    if(q==='motive')dialog('«Илья обещал написать о моей победе. Вместо этого назвал меня участницей договорного боя. Моей сестре нужна операция, а после такой статьи я лишилась бы всех контрактов».');
    if(q==='proof'){state.contradiction=true;dialog('Соколова опускает глаза. «Ладно, я вернулась. Хотела забрать его телефон и удалить запись. Но когда уходила, он ещё дышал». Она назвала устройство, которое нашли рядом с жертвой. Через телефон в кабинете следователя можно запросить восстановление записи и экспертизу кубка.');}
    if(q==='audio')dialog('«Он обещал не упоминать сестру… Я схватила кубок. Думала, он отступит». Соколова замолкает. Запись опровергает её первоначальную версию, а экспертиза связывает её с орудием убийства.');
    if(q==='verdict')verdict();
  });
}
function verdict(){panel(`<div class="eyebrow">РЕШЕНИЕ СЛЕДОВАТЕЛЯ</div><h2>Кто ответит за убийство?</h2><p>Обвинение требует доказательств. Ваше решение завершит дело.</p><button class="choice" id="accuse">Обвинить Марину Соколову</button><button class="choice" id="free">Освободить Соколову — доказательств недостаточно</button><button class="choice" id="continue">Продолжить расследование</button>`);$('#continue').onclick=()=>dialog();$('#accuse').onclick=()=>ending(state.evidence.size===3&&state.contradiction?'solved':'weak');$('#free').onclick=()=>ending('free');}
function ending(result){state.ended=true;const endings={solved:['Дело раскрыто','Журнал доступа, запись и экспертиза кубка подтверждают обвинение. Соколова задержана по подозрению в убийстве. Материалы Громова переданы редакции: расследование договорных боёв продолжится.'],weak:['Обвинение рассыпалось','Обвинение выдвинуто без полной цепочки доказательств. Прокурор вернул дело на дополнительное расследование. Соколова освобождена, а ключевые свидетели больше не выходят на связь.'],free:['Дело осталось открытым','Соколова покинула участок. Наутро служебный журнал клуба оказался стёрт. Без собранных вовремя доказательств гибель Громова остаётся нераскрытой.']};panel(`<div class="eyebrow">НОЧНАЯ СМЕНА / ИТОГ ДЕЛА</div><h2>${endings[result][0]}</h2><p class="lead">${endings[result][1]}</p><div class="badge">СОБРАНО УЛИК: ${state.evidence.size}/3</div><button class="primary" id="restart">НАЧАТЬ ЗАНОВО</button>`);$('#restart').onclick=()=>{state.evidence.clear();state.contradiction=false;state.ended=false;$('#count').textContent='0/3';exitRoom();close();intro();};}
function enter(type){release();state.mode=type;room.hidden=false;$('#crosshair').hidden=true;$('#hint').textContent='';$('#location').textContent=type==='office'?'УЧАСТОК № 7 · КАБИНЕТ СЛЕДОВАТЕЛЯ':'УЧАСТОК № 7 · КОМНАТА ДОПРОСА';$('#controls').textContent='МЫШЬ — осмотр и взаимодействие / ESC — пауза';room.innerHTML=`<div class="scene">${art(type)}</div><div class="room-caption">${type==='office'?'01 / МАТЕРИАЛЫ РАССЛЕДОВАНИЯ':'02 / ПОКАЗАНИЯ'}<h2>${type==='office'?'Кабинет следователя':'Комната допроса'}</h2></div><button class="back">← В КОРИДОР</button>`;$('.back').onclick=()=>{exitRoom();captureMouse();};const spots=type==='office'?[['Папка дела',34,70,15,14,()=>collect('file')],['Доска улик',68,18,25,34,()=>collect('log')],['Телефон · экспертиза',66,72,10,11,()=>{if(state.contradiction)collect('record');else panel('<div class="eyebrow">ЭКСПЕРТНЫЙ ОТДЕЛ</div><h2>Нужна зацепка</h2><p>Сначала изучите журнал пропусков и предъявите его подозреваемому. Его ответ поможет определить, что искать экспертам.</p>');}]]:[['Допросить Соколову',38,17,26,58,()=>dialog()],['Протокол допроса',15,76,26,15,()=>dialog()],['Материалы дела',75,77,12,15,journal]];for(const [label,x,y,w,h,fn]of spots){const b=document.createElement('button');b.className='hotspot';b.setAttribute('aria-label',label);b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;b.innerHTML=`<span>${label}</span>`;b.onclick=fn;room.append(b);}}
function exitRoom(){state.mode='corridor';room.hidden=true;$('#crosshair').hidden=false;$('#location').textContent='УЧАСТОК № 7 · 2 ЭТАЖ';$('#controls').textContent='W A S D — движение / МЫШЬ — обзор / ЛКМ — открыть дверь';}
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;const scene=new THREE.Scene();scene.background=new THREE.Color('#101b22');scene.fog=new THREE.Fog('#101b22',8,25);const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.1,40);camera.position.set(0,1.65,5);camera.rotation.order='YXZ';const {doors,interactables,updateStreet}=createCorridor(scene,renderer);
const ray=new THREE.Raycaster(),keys=new Set();let target=null,busy=false,yaw=0,pitch=0;
document.addEventListener('keydown',e=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if($('#start-story'))return;if(menus.back())return;if(overlay.innerHTML)close();else pause();}if(!overlay.innerHTML)keys.add(e.code);});document.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',release);
document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state.mode==='corridor'&&!overlay.innerHTML){yaw-=e.movementX*.002*menus.preferences.sensitivity;pitch=Math.max(-1.2,Math.min(1.2,pitch-e.movementY*.002*menus.preferences.sensitivity));camera.rotation.set(pitch,yaw,0);tutorial.look(Math.abs(e.movementX)+Math.abs(e.movementY));}});
canvas.addEventListener('click',async()=>{if(state.mode!=='corridor'||overlay.innerHTML||busy)return;sound();if(target){if(target.userData.type==='savePhone'){savePhone();return;}if(target.userData.type==='locked'){toast('Архив опечатан. Начните с кабинета следователя.');return;}busy=true;release();const selected=target;const hinge=selected.userData.hinge;const start=hinge.rotation.y;let t=0;const animate=()=>{t+=.07;hinge.rotation.y=start-Math.min(t,1)*1.15;if(t<1)requestAnimationFrame(animate);else{enter(selected.userData.type);hinge.rotation.y=start;busy=false;}};animate();}else{await captureMouse();}});
function pause(){menus.pause();}
const SAVE_KEY='night-shift-last-round-save-v1';
function readSave(){try{const s=JSON.parse(localStorage.getItem(SAVE_KEY));if(s?.version!==1||!Array.isArray(s.evidence)||s.evidence.some(id=>!Object.hasOwn(evidence,id))||typeof s.contradiction!=='boolean'||!Array.isArray(s.position)||s.position.length!==3||!s.position.every(Number.isFinite)||!Number.isFinite(s.yaw)||!Number.isFinite(s.pitch))return null;return s;}catch{return null;}}
function savePhone(){
  panel(`<div class="eyebrow">БЕЛЫЙ ТЕЛЕФОН / ЛИНИЯ СОХРАНЕНИЯ</div><h2>Наберите номер</h2><p>Номер дежурной линии — <strong>007</strong>. Звонок сохраняет улики, результаты допроса и ваше место в коридоре на этом устройстве.</p><output class="phone-display" id="dial-display">— — —</output><div class="dial-pad">${['1','2','3','4','5','6','7','8','9','⌫','0','☎'].map(k=>`<button class="dial-key" data-digit="${k}" aria-label="${k==='☎'?'Позвонить':k==='⌫'?'Удалить цифру':'Цифра '+k}">${k}</button>`).join('')}</div><p id="dial-status" role="status"></p>`);
  let digits='';const display=$('#dial-display'),status=$('#dial-status');
  document.querySelectorAll('[data-digit]').forEach(button=>button.onclick=()=>{
    const digit=button.dataset.digit;
    if(digit==='☎'){
      if(digits!=='007'){status.textContent='Номер не отвечает. Для сохранения наберите 007.';return;}
      try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,evidence:[...state.evidence],contradiction:state.contradiction,position:camera.position.toArray(),yaw,pitch,tutorial:tutorial.snapshot}));status.textContent='Дежурный: «Принято. Прогресс сохранён». В главном меню доступно «Продолжить».';toast('Игра сохранена');}
      catch{status.textContent='Не удалось сохранить. Браузер запрещает локальное хранилище.';}
    }else{digits=digit==='⌫'?digits.slice(0,-1):digits.length<3?digits+digit:digits;display.textContent=digits||'— — —';status.textContent='';}
  });
}
function resetGame(){state.evidence.clear();state.contradiction=false;state.ended=false;$('#count').textContent='0/3';camera.position.set(.65,1.65,4);yaw=-Math.PI/2;pitch=0;camera.rotation.set(pitch,yaw,0);target=null;exitRoom();sound();tutorial.finish();
  panel('<div class="eyebrow">ДЕЛО № 041 · ПОСЛЕДНИЙ РАУНД</div><h2>Ваша ночная смена</h2><p class="lead">Вы — старший следователь отдела тяжких преступлений. Сегодня вы принимаете ночную смену в участке № 7.</p><p>После боксёрского турнира убит журналист Илья Громов. Он расследовал договорные бои. Подозреваемую, Марину «Сирень» Соколову, уже доставили в комнату допроса.</p><p>Вам предстоит изучить материалы дела, проверить её показания и решить, достаточно ли улик для обвинения. Лестница на первый этаж закрыта — расследование начинается здесь.</p><button class="primary" id="start-story">Продолжить</button>');$('.close').hidden=true;$('#start-story').onclick=()=>{tutorial.start();close();captureMouse();};
}
function loadGame(saved){state.evidence=new Set(saved.evidence);state.contradiction=saved.contradiction;state.ended=false;$('#count').textContent=`${state.evidence.size}/3`;camera.position.fromArray(saved.position);camera.position.x=THREE.MathUtils.clamp(camera.position.x,-2.35,2.35);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-16.5,6.5);if(Math.abs(camera.position.x)<1.43&&camera.position.z< -15.03)camera.position.z=-15;yaw=saved.yaw;pitch=THREE.MathUtils.clamp(saved.pitch,-1.2,1.2);camera.rotation.set(pitch,yaw,0);target=null;tutorial.restore(saved.tutorial);exitRoom();sound();captureMouse();}
let sceneRendered=false;
const menus=createMenus({panel,clear:close,readSave,removeSave:()=>localStorage.removeItem(SAVE_KEY),startNew:resetGame,resume:loadGame,apply:preferences=>{sceneRendered=false;renderer.toneMappingExposure=1.25;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.needsUpdate=true;if(audioGain&&audio)audioGain.gain.setTargetAtTime(.028*preferences.volume/100,audio.currentTime,.05);},stopSound:()=>{if(audio)audio.suspend().catch(()=>{});}});
function intro(){menus.main();}
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(menus.playing&&state.mode==='corridor'&&!overlay.innerHTML&&!busy){let x=0,z=0;if(keys.has('KeyW'))z-=1;if(keys.has('KeyS'))z+=1;if(keys.has('KeyA'))x-=1;if(keys.has('KeyD'))x+=1;const len=Math.hypot(x,z)||1;const dx=(x*Math.cos(yaw)+z*Math.sin(yaw))/len*dt*2.6,dz=(-x*Math.sin(yaw)+z*Math.cos(yaw))/len*dt*2.6;const oldX=camera.position.x,oldZ=camera.position.z;const canWalk=(nx,nz)=>nz>=-16.5&&nz<=6.5&&(nx>=-2.35&&nx<=2.35)&&!(Math.abs(nx)<1.43&&nz< -15.03);if(canWalk(camera.position.x+dx,camera.position.z))camera.position.x+=dx;if(canWalk(camera.position.x,camera.position.z+dz))camera.position.z+=dz;tutorial.movement(Math.hypot(camera.position.x-oldX,camera.position.z-oldZ));ray.setFromCamera(new THREE.Vector2(0,0),camera);const hit=ray.intersectObjects(interactables)[0];target=hit&&hit.distance<2.6?hit.object:null;$('#hint').textContent='';}tutorial.update(state.mode,state.evidence);tutorial.visibility(menus.playing&&!overlay.innerHTML&&!state.ended);if(!menus.exited&&state.mode==='corridor'&&(!overlay.innerHTML||!sceneRendered)){updateStreet(now/1000);renderer.render(scene,camera);sceneRendered=true;}}requestAnimationFrame(frame);window.addEventListener('resize',()=>{sceneRendered=false;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});intro();
if (import.meta.env.DEV) window.__nightShift = { state, camera, menus, renderer, tutorial, get target(){return target;} };
