const SETTINGS_KEY='night-shift-settings-v1';
const defaults={volume:65,sensitivity:1,brightness:1.25,quality:'medium'};
function loadSettings(){try{const s=JSON.parse(localStorage.getItem(SETTINGS_KEY));return {volume:Number.isFinite(s?.volume)?Math.max(0,Math.min(100,s.volume)):65,sensitivity:Number.isFinite(s?.sensitivity)?Math.max(.5,Math.min(2,s.sensitivity)):1,brightness:Number.isFinite(s?.brightness)?Math.max(.7,Math.min(1.7,s.brightness)):1.25,quality:['low','medium','high'].includes(s?.quality)?s.quality:'medium'};}catch{return {...defaults};}}
export function createMenus({panel,clear,readSave,startNew,resume,apply,stopSound}){
  const $=s=>document.querySelector(s);
  let screen='main',parent='main',playing=false,exited=false;
  const preferences=loadSettings();apply(preferences);
  function show(html){panel(html);$('.close').hidden=true;}
  function activate(){screen='game';playing=true;exited=false;document.body.classList.remove('in-menu');clear();}
  function main(){screen='main';playing=false;exited=false;document.body.classList.add('in-menu');stopSound();const saved=readSave();
    show(`<div class="eyebrow">ДЕТЕКТИВ / ДЕЛО № 041</div><h1>Ночная<br>смена</h1><p class="menu-tagline">У каждого есть версия. Только одна — правда.</p><nav class="main-actions" aria-label="Главное меню"><button class="menu-action" id="new-game">Новая игра <span aria-hidden="true">01</span></button><button class="menu-action" id="load-game" ${saved?'':'disabled'}>Продолжить <span aria-hidden="true">02</span></button><button class="menu-action" id="settings">Настройки <span aria-hidden="true">03</span></button><button class="menu-action" id="author">Автор <span aria-hidden="true">04</span></button><button class="menu-action" id="quit">Выход <span aria-hidden="true">05</span></button></nav><div class="menu-note">${saved?`Сохранение доступно · улик ${saved.evidence.length}/3`:'Нет сохранения · сохраните игру звонком на 007'}</div>`);
    $('.panel').classList.add('main-menu');$('#new-game').onclick=()=>{activate();startNew();};$('#load-game').onclick=()=>{const current=readSave();if(current){activate();resume(current);}else main();};$('#settings').onclick=()=>settings('main');$('#author').onclick=author;$('#quit').onclick=quit;
  }
  function pause(){screen='pause';show('<div class="eyebrow">НОЧНАЯ СМЕНА</div><h2>Пауза</h2><button class="choice" id="resume-game">Вернуться в игру</button><button class="choice" id="pause-settings">Настройки</button><button class="choice" id="to-main">Главное меню</button><p>Прогресс сохраняется через телефон. Выход в меню не создаёт сохранение.</p>');$('#resume-game').onclick=()=>{screen='game';clear();};$('#pause-settings').onclick=()=>settings('pause');$('#to-main').onclick=main;}
  function settings(from){parent=from;screen='settings';show(`<div class="eyebrow">НОЧНАЯ СМЕНА / ПАРАМЕТРЫ</div><h2>Настройки</h2><label class="setting">Громкость <output id="volume-value">${preferences.volume}%</output><input id="volume" type="range" min="0" max="100" value="${preferences.volume}"></label><label class="setting">Чувствительность мыши <output id="sensitivity-value">${preferences.sensitivity.toFixed(1)}</output><input id="sensitivity" type="range" min="0.5" max="2" step="0.1" value="${preferences.sensitivity}"></label><label class="setting">Яркость <output id="brightness-value">${preferences.brightness.toFixed(2)}</output><input id="brightness" type="range" min="0.7" max="1.7" step="0.05" value="${preferences.brightness}"></label><label class="setting">Качество графики<select id="quality"><option value="low">Низкое — без теней</option><option value="medium">Среднее</option><option value="high">Высокое</option></select></label><button class="choice" id="fullscreen">${document.fullscreenElement?'Выйти из полного экрана':'Полный экран'}</button><div class="menu-note" id="setting-status" role="status">Изменения применяются сразу и сохраняются в браузере.</div><div class="menu-buttons"><button class="choice" id="reset-settings">По умолчанию</button><button class="primary" id="back-menu">Назад</button></div>`);
    $('#quality').value=preferences.quality;
    function change(key,value){preferences[key]=value;apply(preferences);if(key!=='quality')$('#'+key+'-value').textContent=key==='volume'?value+'%':value.toFixed(key==='brightness'?2:1);try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(preferences));$('#setting-status').textContent='Настройки сохранены.';}catch{$('#setting-status').textContent='Применено. Браузер не разрешает сохранять настройки.';}}
    for(const key of ['volume','sensitivity','brightness'])$('#'+key).oninput=e=>change(key,Number(e.target.value));$('#quality').onchange=e=>change('quality',e.target.value);
    $('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();$('#fullscreen').textContent=document.fullscreenElement?'Выйти из полного экрана':'Полный экран';}catch{$('#setting-status').textContent='Полный экран недоступен в этом браузере.';}};
    $('#reset-settings').onclick=()=>{Object.assign(preferences,defaults);apply(preferences);try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(preferences));}catch{}settings(from);};$('#back-menu').onclick=()=>from==='pause'?pause():main();
  }
  function author(){screen='author';show('<div class="eyebrow">НОЧНАЯ СМЕНА / АВТОР</div><h2>За кулисами дела</h2><p class="lead">Автор проекта и идеи:<br><strong>lagutrkinadarina-dotcom</strong></p><p>Прототип создан совместно с Codex. Коридор, предметы и кабинеты созданы для этой игры.</p><a class="author-link" href="https://github.com/lagutrkinadarina-dotcom/katya" target="_blank" rel="noopener noreferrer">Открыть проект на GitHub ↗</a><div class="rule"></div><button class="primary" id="author-back">Назад</button>');$('#author-back').onclick=main;}
  function quit(){screen='exit';playing=false;exited=true;document.body.classList.add('in-menu');stopSound();if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});show('<div class="eyebrow">НОЧНАЯ СМЕНА</div><h2>Смена окончена</h2><p>Игра остановлена. Сохранение осталось в браузере. Можно закрыть вкладку или вернуться в меню.</p><button class="primary" id="return-menu">Вернуться в меню</button>');$('#return-menu').onclick=main;if(window.opener)window.close();}
  function back(){if(screen==='settings'){parent==='pause'?pause():main();return true;}if(screen==='author'||screen==='exit'){main();return true;}if(screen==='pause'){screen='game';clear();return true;}return screen==='main';}
  return {main,pause,back,preferences,get playing(){return playing;},get exited(){return exited;}};
}
